PKGDIR	?= .
L4DIR	?= $(PKGDIR)/../../l4

# the default is to build the listed directories, provided that they
# contain a Makefile. If you need to change this, uncomment the following
# line and adapt it.
# TARGET = idl include src lib server examples doc
TARGET = diction src doc

include $(L4DIR)/mk/subdir.mk
