name: "Build"
on:
  pull_request:
  push:
  merge_group:

jobs:
  # Builds the Nix derivation.
  nix_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .
      #   -s: test if this is a file and if it has a size.
      - run: test -s result/diplom.pdf

  # Tests the regular build but with a toolchain from the Nix shell.
  nix_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -i --command bash -c "make"
      - run: nix develop -i --command bash -c "make stats"

  # Builds with a regular toolchain via latexmk.
  regular_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          # options listed here:
          # https://github.com/xu-cheng/latex-action
          root_file: diplom.tex
          latexmk_use_lualatex: true
          # required when using the "minted" package for beautiful styled code
          # latexmk_shell_escape: true

  # checkbiw and check-french-spacing must execute without error
  check_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        # additionally: check out submodules
        with:
          submodules: recursive
      - name: install make
        run: sudo apt update && sudo apt install make
      - name: make check-french-spacing
        run: make check-french-spacing
      - name: install diction
        run: sudo apt update && sudo apt install diction
      - name: make checkbiw
        run: make checkbiw
